[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self'; script-src 'self' 'https://identity.netlify.com' 'https://unpkg.com'; connect-src 'self'; img-src 'self'; base-uri 'self';"
